In [6]:
import pandas
from keras.models import Sequential
from keras.layers.core import Dense, Activation

# load dataset
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

dataset = pd.read_csv("diabetes.csv", header=None).values

X_train, X_test, Y_train, Y_test = train_test_split(dataset[:,0:8], dataset[:,8],
                                                    test_size=0.25, random_state=87)
np.random.seed(155)
my_first_nn = Sequential()    # create model
my_first_nn.add(Dense(40, input_dim=8, activation='relu'))# hidden layer
my_first_nn.add(Dense(30, activation='sigmoid')) # hidden layer
my_first_nn.add(Dense(1, activation='sigmoid')) # output layer
my_first_nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])
my_first_nn_fitted = my_first_nn.fit(X_train, Y_train, epochs=100,
                                     initial_epoch=0)
print(my_first_nn.summary())
print(my_first_nn.evaluate(X_test, Y_test))

Epoch 1/100
576/576 [==============================] - 1s 928us/step - loss: 0.6443 - acc: 0.6615
Epoch 2/100
576/576 [==============================] - 0s 43us/step - loss: 0.6248 - acc: 0.6615
Epoch 3/100
576/576 [==============================] - 0s 42us/step - loss: 0.6145 - acc: 0.6615
Epoch 4/100
576/576 [==============================] - 0s 44us/step - loss: 0.6037 - acc: 0.6719
Epoch 5/100
576/576 [==============================] - 0s 48us/step - loss: 0.5961 - acc: 0.6753
Epoch 6/100
576/576 [==============================] - 0s 49us/step - loss: 0.5927 - acc: 0.6649
Epoch 7/100
576/576 [==============================] - 0s 47us/step - loss: 0.5894 - acc: 0.6771
Epoch 8/100
576/576 [==============================] - 0s 48us/step - loss: 0.5902 - acc: 0.6667
Epoch 9/100
576/576 [==============================] - 0s 47us/step - loss: 0.5851 - acc: 0.6753
Epoch 10/100
576/576 [==============================] - 0s 58us/step - loss: 0.5825 - acc: 0.6788
Epoch 11/100
576/576 [======

In [7]:
import pandas

from keras.models import Sequential

from keras.layers.core import Dense, Activation

import seaborn as sns

import matplotlib.pyplot as plt



# load dataset

from sklearn.model_selection import train_test_split

import pandas as pd

dataset = pd.read_csv("Breas Cancer.csv")

# print(dataset)



classes = ['Benign', 'Malignant']



X = dataset.iloc[:, 2:32].values

y = dataset.iloc[:, 1].values



print(X)

print(y)



# Encoding categorical data

from sklearn.preprocessing import LabelEncoder

labelencoder_X_1 = LabelEncoder()

y = labelencoder_X_1.fit_transform(y)

print(y)



from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)



from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)

X_test = sc.transform(X_test)



my_first_nn = Sequential() # create model

my_first_nn.add(Dense(20, input_dim=30, activation='relu')) # hidden layer

my_first_nn.add(Dense(15, activation='relu')) # added layer

my_first_nn.add(Dense(10, activation='relu')) # added layer

my_first_nn.add(Dense(5, activation='relu')) # added layer



my_first_nn.add(Dense(1, activation='sigmoid')) # output layer

my_first_nn.compile(loss='binary_crossentropy', optimizer='adam',metrics=['acc'])

my_first_nn_fitted = my_first_nn.fit(X_train, y_train, epochs=100, verbose=0,

                                     initial_epoch=0)

print(my_first_nn.summary())

print(my_first_nn.evaluate(X_test, y_test, verbose=0))

y_pred = my_first_nn.predict(X_test)

y_pred = (y_pred > 0.5)







[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B'
 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B'
 'B' 'B'

In [3]:
import pandas
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from sklearn.preprocessing import LabelEncoder
import numpy as np
le = LabelEncoder()
from sklearn.preprocessing import StandardScaler
scaler =StandardScaler()


from sklearn.model_selection import train_test_split
import pandas as pd
dataset = pd.read_csv("Breas Cancer.csv").values
x = dataset[:,1:2]
x = le.fit_transform(x)
X_train, X_test, Y_train, Y_test = train_test_split(dataset[:,2:32], x,
                                                    test_size=0.25, random_state=87)
np.random.seed(77)
my_first_nn = Sequential() # create model
my_first_nn.add(Dense(64, input_dim=30, activation='relu')) # hidden layer
my_first_nn.add(Dense(32, activation='relu'))
my_first_nn.add(Dense(1, activation='sigmoid')) # output layer
my_first_nn.compile(loss='binary_crossentropy', optimizer='adadelta', metrics=['acc'])
my_first_nn_fitted = my_first_nn.fit(X_train, Y_train, epochs=10, initial_epoch=0)
print(my_first_nn.summary())
print(my_first_nn.evaluate(X_test, Y_test))

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Epoch 1/10
426/426 [==============================] - 0s 876us/step - loss: 6.1294 - acc: 0.6197
Epoch 2/10
426/426 [==============================] - 0s 54us/step - loss: 6.1294 - acc: 0.6197
Epoch 3/10
426/426 [==============================] - 0s 51us/step - loss: 6.1294 - acc: 0.6197
Epoch 4/10
426/426 [==============================] - 0s 66us/step - loss: 6.1294 - acc: 0.6197
Epoch 5/10
426/426 [==============================] - 0s 58us/step - loss: 6.1294 - acc: 0.6197
Epoch 6/10
426/426 [==============================] - 0s 61us/step - loss: 6.1294 - acc: 0.6197
Epoch 7/10
426/426 [==============================] - 0s 57us/step - loss: 6.1294 - acc: 0.6197
Epoch 8/10
426/426 [==============================] - 0s 54us/step - loss: 6.1294 - acc: 0.6197
Epoch 9/10
426/426 [==============================] - 0s 54us/step - loss: 6.1294 - acc: 0.6197
Epoch 10/10
426/426 [==============================] - 0s 52us/step - loss: 6.1294 - acc: 0.6197
Model: "sequential_3"
________________